version: 0.0
os: linux
files:
  - source: src/
    destination: /var/www/node-test
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/package.sh
      timeout: 300
      runas: root    
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300
      runas: root
