version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10 
    commands:
    
      # Install dependencies needed for running tests
      - cd src && npm install && cd ..
 
artifacts:
  files:
    - '**/*'
